export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export const REQUEST_SOURCE_DATA = "REQUEST_SOURCE_DATA";
export const RECEIVE_SOURCE_DATA = "RECEIVE_SOURCE_DATA";
export const REQUEST_POPULAR_DATA = "REQUEST_POPULAR_DATA";
export const RECEIVE_POPULAR_DATA = "RECEIVE_POPULAR_DATA";
export const REQUEST_MOVDET_DATA = "REQUEST_MOVDET_DATA";
export const RECEIVE_MOVDET_DATA = "RECEIVE_MOVDET_DATA";
export const REQUEST_REVIEW_DATA = "REQUEST_REVIEW_DATA";
export const RECEIVE_REVIEW_DATA = "RECEIVE_REVIEW_DATA";
export const REQUEST_FILTER_DATA = "REQUEST_FILTER_DATA";
export const RECEIVE_FILTER_DATA = "RECEIVE_FILTER_DATA";
export const REQUEST_SEARCH_DATA = "REQUEST_SEARCH_DATA";
export const RECEIVE_SEARCH_DATA = "RECEIVE_SEARCH_DATA";

