export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export const REQUEST_SOURCE_DATA = "REQUEST_SOURCE_DATA";
export const RECEIVE_SOURCE_DATA = "RECEIVE_SOURCE_DATA";